name: Submit latest Android build to closed testing

on:
  workflow_dispatch: {}

jobs:
  get_android_build:
    name: Find latest production AAB
    type: get-build
    params:
      platform: android
      profile: production
      distribution: store

  submit_android:
    name: Deploy latest AAB to Google Play closed testing
    needs:
      - get_android_build
    type: submit
    env:
      EXPO_DEBUG: "1"
    params:
      profile: closed
      build_id: ${{ needs.get_android_build.outputs.build_id }}
