create table if not exists public.place_activity (
  id bigint generated by default as identity primary key,
  place_id text not null,
  name text not null,
  region text not null default '전국',
  city text,
  category text not null,
  address text,
  image_url text,
  event_type text not null check (event_type in ('view', 'detail', 'outbound', 'favorite')),
  visitor_id text not null,
  event_bucket bigint not null,
  created_at timestamptz not null default now()
);

create unique index if not exists place_activity_deduplicate_idx
  on public.place_activity (place_id, event_type, visitor_id, event_bucket);
create index if not exists place_activity_place_created_idx
  on public.place_activity (place_id, created_at desc);

create table if not exists public.trending_place_scores (
  place_id text primary key,
  name text not null,
  region text not null default '전국',
  city text,
  category text not null,
  address text,
  image_url text,
  score numeric not null default 0,
  view_count bigint not null default 0,
  detail_count bigint not null default 0,
  outbound_count bigint not null default 0,
  favorite_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

create or replace view public.live_trending_places as
select
  place_id, name, region, city, category, address, image_url,
  round((score::double precision * power(
    0.5::double precision,
    greatest(0, extract(epoch from (now() - updated_at))) / 259200
  ))::numeric, 2) as score,
  view_count, detail_count, outbound_count, favorite_count, updated_at
from public.trending_place_scores;

create or replace function public.update_trending_place_score()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  event_weight numeric;
begin
  event_weight := case new.event_type
    when 'view' then 1 when 'detail' then 2 when 'outbound' then 3
    when 'favorite' then 5 else 0 end;

  insert into public.trending_place_scores (
    place_id, name, region, city, category, address, image_url,
    score, view_count, detail_count, outbound_count, favorite_count, updated_at
  ) values (
    new.place_id, new.name, new.region, new.city, new.category, new.address, new.image_url,
    event_weight,
    case when new.event_type = 'view' then 1 else 0 end,
    case when new.event_type = 'detail' then 1 else 0 end,
    case when new.event_type = 'outbound' then 1 else 0 end,
    case when new.event_type = 'favorite' then 1 else 0 end,
    now()
  )
  on conflict (place_id) do update set
    name = excluded.name,
    region = excluded.region,
    city = excluded.city,
    category = excluded.category,
    address = coalesce(excluded.address, trending_place_scores.address),
    image_url = coalesce(excluded.image_url, trending_place_scores.image_url),
    score = trending_place_scores.score + event_weight,
    view_count = trending_place_scores.view_count + case when new.event_type = 'view' then 1 else 0 end,
    detail_count = trending_place_scores.detail_count + case when new.event_type = 'detail' then 1 else 0 end,
    outbound_count = trending_place_scores.outbound_count + case when new.event_type = 'outbound' then 1 else 0 end,
    favorite_count = trending_place_scores.favorite_count + case when new.event_type = 'favorite' then 1 else 0 end,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists place_activity_update_trending_score on public.place_activity;
create trigger place_activity_update_trending_score
after insert on public.place_activity
for each row execute function public.update_trending_place_score();

create table if not exists public.keyword_search_events (
  id bigint generated by default as identity primary key,
  keyword text not null check (char_length(keyword) between 2 and 60),
  visitor_key text not null,
  source text not null default 'search' check (source in ('search', 'trend')),
  event_bucket bigint not null,
  created_at timestamptz not null default now()
);

create unique index if not exists keyword_search_events_deduplicate_idx
  on public.keyword_search_events (keyword, visitor_key, source, event_bucket);
create index if not exists keyword_search_events_created_idx
  on public.keyword_search_events (created_at desc);

create or replace function public.get_live_trending_keywords(
  window_minutes integer default 30,
  result_limit integer default 6
)
returns table (
  keyword text,
  search_count bigint,
  current_score numeric,
  previous_score numeric,
  current_rank bigint,
  previous_rank bigint
)
language sql
stable
set search_path = public
as $$
  with defaults(keyword, fallback_order) as (
    values
      ('서울 데이트'::text, 1), ('부산 관광지'::text, 2),
      ('제주 카페'::text, 3), ('수원 음식'::text, 4),
      ('비 오는 날'::text, 5), ('주말 나들이'::text, 6)
  ),
  observed_events as (
    select k.keyword, k.created_at,
      case when k.source = 'search' then 5::numeric else 3::numeric end as weight
    from public.keyword_search_events k
    where k.created_at >= now() - interval '24 hours'
    union all
    select concat_ws(' ', nullif(p.region, '전국'), p.category), p.created_at,
      case p.event_type when 'favorite' then 4::numeric when 'outbound' then 3::numeric
        when 'detail' then 2::numeric else 1::numeric end
    from public.place_activity p
    where p.created_at >= now() - interval '24 hours'
  ),
  all_keywords as (
    select d.keyword, d.fallback_order from defaults d
    union
    select distinct e.keyword, 999 from observed_events e where e.keyword <> ''
  ),
  scores as (
    select k.keyword, k.fallback_order,
      coalesce(sum(e.weight), 0)::bigint as search_count,
      coalesce(sum(e.weight) filter (
        where e.created_at >= now() - make_interval(mins => greatest(5, least(window_minutes, 120)))
      ), 0) as current_score,
      coalesce(sum(e.weight) filter (
        where e.created_at < now() - make_interval(mins => greatest(5, least(window_minutes, 120)))
          and e.created_at >= now() - make_interval(mins => greatest(10, least(window_minutes * 2, 240)))
      ), 0) as previous_score
    from all_keywords k
    left join observed_events e on e.keyword = k.keyword
    group by k.keyword, k.fallback_order
  ),
  ranked as (
    select s.*,
      row_number() over (order by s.current_score desc, s.search_count desc, s.fallback_order, s.keyword) as current_rank,
      row_number() over (order by s.previous_score desc, s.search_count desc, s.fallback_order, s.keyword) as previous_rank
    from scores s
  )
  select r.keyword, r.search_count, r.current_score, r.previous_score,
         r.current_rank, r.previous_rank
  from ranked r
  order by r.current_rank
  limit greatest(1, least(result_limit, 10));
$$;

alter table public.place_activity disable row level security;
alter table public.trending_place_scores disable row level security;
alter table public.keyword_search_events disable row level security;
