create extension if not exists pgcrypto;

create table if not exists public.place_categories (
  id bigint generated by default as identity primary key,
  code text not null unique check (char_length(code) between 1 and 80),
  name text not null check (char_length(name) between 1 and 80),
  parent_id bigint references public.place_categories(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.place_regions (
  id bigint generated by default as identity primary key,
  region_name text not null check (char_length(region_name) between 1 and 80),
  city_name text not null default '' check (char_length(city_name) <= 120),
  area_code text not null default '' check (char_length(area_code) <= 20),
  sigungu_code text not null default '' check (char_length(sigungu_code) <= 30),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(region_name, city_name, area_code, sigungu_code)
);

create table if not exists public.place_sources (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.places(id) on delete cascade,
  provider text not null check (char_length(provider) between 1 and 40),
  external_id text not null check (char_length(external_id) between 1 and 180),
  external_url text check (external_url is null or char_length(external_url) <= 1200),
  source_modified_at text,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, external_id),
  unique(place_id, provider)
);

create index if not exists place_sources_place_idx on public.place_sources(place_id);
create index if not exists place_sources_provider_idx on public.place_sources(provider, external_id);

create table if not exists public.place_images (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.places(id) on delete cascade,
  image_url text not null check (char_length(image_url) between 1 and 1200),
  source text not null default 'unknown' check (char_length(source) between 1 and 40),
  license_type text check (license_type is null or char_length(license_type) <= 120),
  attribution text check (attribution is null or char_length(attribution) <= 500),
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique(place_id, image_url)
);

create index if not exists place_images_place_primary_idx on public.place_images(place_id, is_primary desc);

create table if not exists public.place_search_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text check (visitor_id is null or char_length(visitor_id) <= 120),
  keyword text not null default '' check (char_length(keyword) <= 200),
  region text check (region is null or char_length(region) <= 80),
  city text check (city is null or char_length(city) <= 120),
  category text check (category is null or char_length(category) <= 80),
  result_count integer check (result_count is null or result_count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists place_search_events_created_idx on public.place_search_events(created_at desc);
create index if not exists place_search_events_keyword_idx on public.place_search_events(keyword, created_at desc);

create table if not exists public.place_click_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text check (visitor_id is null or char_length(visitor_id) <= 120),
  provider text not null default 'tourapi' check (char_length(provider) <= 40),
  external_id text not null check (char_length(external_id) between 1 and 180),
  event_type text not null default 'view' check (event_type in ('view','detail','outbound','favorite','route','share','map','reservation')),
  source_screen text check (source_screen is null or char_length(source_screen) <= 120),
  created_at timestamptz not null default now()
);

create index if not exists place_click_events_place_idx on public.place_click_events(provider, external_id, created_at desc);
create index if not exists place_click_events_created_idx on public.place_click_events(created_at desc);

create table if not exists public.place_popularity (
  provider text not null,
  external_id text not null,
  views_1d bigint not null default 0,
  views_7d bigint not null default 0,
  views_30d bigint not null default 0,
  favorites_30d bigint not null default 0,
  routes_30d bigint not null default 0,
  shares_30d bigint not null default 0,
  score numeric(14,4) not null default 0,
  calculated_at timestamptz not null default now(),
  primary key(provider, external_id)
);

alter table public.place_categories enable row level security;
alter table public.place_regions enable row level security;
alter table public.place_sources enable row level security;
alter table public.place_images enable row level security;
alter table public.place_search_events enable row level security;
alter table public.place_click_events enable row level security;
alter table public.place_popularity enable row level security;

revoke all on public.place_categories, public.place_regions, public.place_sources, public.place_images, public.place_search_events, public.place_click_events, public.place_popularity from anon, authenticated;

grant select on public.place_categories, public.place_regions, public.place_sources, public.place_images, public.place_popularity to service_role;
grant select, insert, update, delete on public.place_search_events, public.place_click_events to service_role;

insert into public.place_categories(code, name)
select distinct lower(regexp_replace(category, '[^[:alnum:]가-힣]+', '_', 'g')), category
from public.tour_places
where active and category is not null and btrim(category) <> ''
on conflict (code) do update set name = excluded.name, updated_at = now();

insert into public.place_regions(region_name, city_name, area_code, sigungu_code)
select distinct coalesce(nullif(btrim(region), ''), '전국'), coalesce(btrim(city), ''), coalesce(btrim(area_code), ''), coalesce(btrim(sigungu_code), '')
from public.tour_places
where active
on conflict (region_name, city_name, area_code, sigungu_code) do update set active = true, updated_at = now();

insert into public.place_sources(place_id, provider, external_id, external_url, last_synced_at)
select id, coalesce(nullif(lower(btrim(source)), ''), 'manual'), coalesce(nullif(btrim(external_id), ''), id::text), source_url, coalesce(last_synced_at, updated_at, now())
from public.places
on conflict (provider, external_id) do update set place_id = excluded.place_id, external_url = excluded.external_url, last_synced_at = excluded.last_synced_at, updated_at = now();

insert into public.place_images(place_id, image_url, source, license_type, is_primary)
select id, thumbnail_url, coalesce(nullif(lower(btrim(source)), ''), 'manual'), image_license, true
from public.places
where thumbnail_url is not null and btrim(thumbnail_url) <> ''
on conflict (place_id, image_url) do update set source = excluded.source, license_type = excluded.license_type, is_primary = true;

create or replace function public.refresh_place_popularity()
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  insert into public.place_popularity(provider, external_id, views_1d, views_7d, views_30d, favorites_30d, routes_30d, shares_30d, score, calculated_at)
  select
    e.provider,
    e.external_id,
    count(*) filter (where e.event_type in ('view','detail') and e.created_at >= now() - interval '1 day'),
    count(*) filter (where e.event_type in ('view','detail') and e.created_at >= now() - interval '7 days'),
    count(*) filter (where e.event_type in ('view','detail') and e.created_at >= now() - interval '30 days'),
    count(*) filter (where e.event_type = 'favorite' and e.created_at >= now() - interval '30 days'),
    count(*) filter (where e.event_type = 'route' and e.created_at >= now() - interval '30 days'),
    count(*) filter (where e.event_type = 'share' and e.created_at >= now() - interval '30 days'),
    (count(*) filter (where e.event_type in ('view','detail') and e.created_at >= now() - interval '7 days'))::numeric
      + (count(*) filter (where e.event_type = 'favorite' and e.created_at >= now() - interval '30 days')) * 4
      + (count(*) filter (where e.event_type = 'route' and e.created_at >= now() - interval '30 days')) * 3
      + (count(*) filter (where e.event_type = 'share' and e.created_at >= now() - interval '30 days')) * 5,
    now()
  from public.place_click_events e
  where e.created_at >= now() - interval '30 days'
  group by e.provider, e.external_id
  on conflict (provider, external_id) do update set
    views_1d = excluded.views_1d,
    views_7d = excluded.views_7d,
    views_30d = excluded.views_30d,
    favorites_30d = excluded.favorites_30d,
    routes_30d = excluded.routes_30d,
    shares_30d = excluded.shares_30d,
    score = excluded.score,
    calculated_at = excluded.calculated_at;
end;
$$;

revoke all on function public.refresh_place_popularity() from public, anon, authenticated;
grant execute on function public.refresh_place_popularity() to service_role;
