create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to service_role;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_by uuid references auth.users(id) on delete set null,
  note text check (note is null or char_length(note) <= 200),
  created_at timestamptz not null default now()
);

create table if not exists public.admin_traffic_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  path text not null check (char_length(path) between 1 and 300),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 255),
  device_type text not null check (device_type in ('desktop', 'mobile', 'tablet')),
  is_authenticated boolean not null default false,
  event_bucket bigint not null,
  created_at timestamptz not null default now()
);

create unique index if not exists admin_traffic_deduplicate_idx
  on public.admin_traffic_events(visitor_id, path, event_bucket);
create index if not exists admin_traffic_created_idx
  on public.admin_traffic_events(created_at desc);
create index if not exists admin_traffic_path_created_idx
  on public.admin_traffic_events(path, created_at desc);

alter table public.admin_users enable row level security;
alter table public.admin_traffic_events enable row level security;

revoke all on public.admin_users from anon, authenticated;
revoke all on public.admin_traffic_events from anon, authenticated;
grant all on public.admin_users, public.admin_traffic_events to service_role;
grant usage, select on sequence public.admin_traffic_events_id_seq to service_role;

-- 기존 프로젝트의 최초 가입 계정을 초기 운영자로 지정합니다.
-- 이후 운영자는 admin_users에 명시적으로 추가해 관리합니다.
insert into public.admin_users (user_id, created_by, note)
select id, id, 'Initial project owner'
from auth.users
order by created_at asc
limit 1
on conflict (user_id) do nothing;

create or replace function private.prune_admin_traffic_events()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.admin_traffic_events
  where created_at < now() - interval '90 days';
  return null;
end;
$$;

drop trigger if exists prune_admin_traffic_events_after_insert
  on public.admin_traffic_events;
create trigger prune_admin_traffic_events_after_insert
after insert on public.admin_traffic_events
for each statement execute function private.prune_admin_traffic_events();

create or replace function public.get_admin_traffic_dashboard(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  safe_days integer := least(greatest(coalesce(p_days, 30), 1), 90);
  today_kst date := timezone('Asia/Seoul', now())::date;
  result jsonb;
begin
  select jsonb_build_object(
    'todayViews', (
      select count(*) from public.admin_traffic_events
      where timezone('Asia/Seoul', created_at)::date = today_kst
    ),
    'todayVisitors', (
      select count(distinct visitor_id) from public.admin_traffic_events
      where timezone('Asia/Seoul', created_at)::date = today_kst
    ),
    'views7d', (
      select count(*) from public.admin_traffic_events
      where created_at >= now() - interval '7 days'
    ),
    'visitors7d', (
      select count(distinct visitor_id) from public.admin_traffic_events
      where created_at >= now() - interval '7 days'
    ),
    'views30d', (
      select count(*) from public.admin_traffic_events
      where created_at >= now() - make_interval(days => safe_days)
    ),
    'visitors30d', (
      select count(distinct visitor_id) from public.admin_traffic_events
      where created_at >= now() - make_interval(days => safe_days)
    ),
    'authenticatedViews30d', (
      select count(*) from public.admin_traffic_events
      where created_at >= now() - make_interval(days => safe_days)
        and is_authenticated
    ),
    'daily', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'date', days.day::text,
          'views', coalesce(stats.views, 0),
          'visitors', coalesce(stats.visitors, 0)
        ) order by days.day
      )
      from generate_series(today_kst - 13, today_kst, interval '1 day') as days(day)
      left join (
        select
          timezone('Asia/Seoul', created_at)::date as day,
          count(*) as views,
          count(distinct visitor_id) as visitors
        from public.admin_traffic_events
        where created_at >= now() - interval '14 days'
        group by 1
      ) stats on stats.day = days.day::date
    ), '[]'::jsonb),
    'topPages', coalesce((
      select jsonb_agg(to_jsonb(top_pages) order by top_pages.views desc)
      from (
        select path, count(*) as views, count(distinct visitor_id) as visitors
        from public.admin_traffic_events
        where created_at >= now() - make_interval(days => safe_days)
        group by path
        order by count(*) desc
        limit 8
      ) top_pages
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(to_jsonb(device_stats) order by device_stats.views desc)
      from (
        select device_type as device, count(*) as views
        from public.admin_traffic_events
        where created_at >= now() - make_interval(days => safe_days)
        group by device_type
      ) device_stats
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.get_admin_traffic_dashboard(integer)
  from public, anon, authenticated;
grant execute on function public.get_admin_traffic_dashboard(integer)
  to service_role;
