create table if not exists public.keyword_search_events (
  id bigint generated by default as identity primary key,
  keyword text not null check (char_length(keyword) between 2 and 60),
  visitor_key text not null,
  source text not null default 'search' check (source in ('search', 'trend')),
  event_bucket bigint not null,
  created_at timestamptz not null default now()
);

create index if not exists keyword_search_events_created_idx
  on public.keyword_search_events (created_at desc);

create index if not exists keyword_search_events_keyword_created_idx
  on public.keyword_search_events (keyword, created_at desc);

create unique index if not exists keyword_search_events_deduplicate_idx
  on public.keyword_search_events (keyword, visitor_key, source, event_bucket);

alter table public.keyword_search_events enable row level security;

drop policy if exists "public can create keyword search events" on public.keyword_search_events;
create policy "public can create keyword search events"
  on public.keyword_search_events
  for insert
  to anon, authenticated
  with check (source in ('search', 'trend'));

drop policy if exists "public can observe keyword search events" on public.keyword_search_events;
create policy "public can observe keyword search events"
  on public.keyword_search_events
  for select
  to anon, authenticated
  using (created_at >= now() - interval '1 hour');

grant insert, select on public.keyword_search_events to anon, authenticated;
grant usage, select on sequence public.keyword_search_events_id_seq to anon, authenticated;

create or replace function public.get_live_trending_keywords(
  window_minutes integer default 30,
  result_limit integer default 6
)
returns table (
  keyword text,
  search_count bigint,
  current_score numeric,
  previous_score numeric,
  current_rank bigint,
  previous_rank bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with defaults(keyword, fallback_order) as (
    values
      ('서울 데이트'::text, 1),
      ('부산 관광지'::text, 2),
      ('제주 카페'::text, 3),
      ('수원 음식'::text, 4),
      ('비 오는 날'::text, 5),
      ('주말 나들이'::text, 6)
  ),
  observed_events as (
    select
      k.keyword,
      k.created_at,
      case when k.source = 'search' then 5::numeric else 3::numeric end as weight
    from public.keyword_search_events k
    where k.created_at >= now() - interval '24 hours'
  ),
  all_keywords as (
    select d.keyword, d.fallback_order from defaults d
    union
    select distinct e.keyword, 999 from observed_events e where e.keyword <> ''
  ),
  scores as (
    select
      k.keyword,
      k.fallback_order,
      coalesce(sum(e.weight), 0)::bigint as search_count,
      coalesce(sum(e.weight) filter (
        where e.created_at >= now() - make_interval(mins => greatest(5, least(window_minutes, 120)))
      ), 0) as current_score,
      coalesce(sum(e.weight) filter (
        where e.created_at < now() - make_interval(mins => greatest(5, least(window_minutes, 120)))
          and e.created_at >= now() - make_interval(mins => greatest(10, least(window_minutes * 2, 240)))
      ), 0) as previous_score
    from all_keywords k
    left join observed_events e on e.keyword = k.keyword
    group by k.keyword, k.fallback_order
  ),
  ranked as (
    select
      s.*,
      row_number() over (
        order by s.current_score desc, s.search_count desc, s.fallback_order, s.keyword
      ) as current_rank,
      row_number() over (
        order by s.previous_score desc, s.search_count desc, s.fallback_order, s.keyword
      ) as previous_rank
    from scores s
  )
  select
    r.keyword,
    r.search_count,
    r.current_score,
    r.previous_score,
    r.current_rank,
    r.previous_rank
  from ranked r
  order by r.current_rank
  limit greatest(1, least(result_limit, 10));
$$;

grant execute on function public.get_live_trending_keywords(integer, integer)
  to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.keyword_search_events;
exception
  when duplicate_object then null;
end $$;
