alter table public.app_service_status
  add column if not exists feature_flags jsonb not null default jsonb_build_object(
    'place_search', true,
    'recommendations', true,
    'office_dining', true,
    'saved_places', true,
    'shared_poll', true,
    'reservations', true,
    'weather', true,
    'navigation', true
  );

alter table public.app_service_status
  drop constraint if exists app_service_status_feature_flags_object;
alter table public.app_service_status
  add constraint app_service_status_feature_flags_object
  check (jsonb_typeof(feature_flags) = 'object');

create table if not exists public.admin_operation_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in (
    'search_no_results', 'place_card_click', 'map_open', 'directions_open',
    'booking_open', 'app_error', 'app_crash', 'api_request'
  )),
  platform text not null check (platform in ('web', 'android', 'ios')),
  visitor_id uuid not null,
  feature text not null check (char_length(feature) between 1 and 60),
  route text check (route is null or char_length(route) <= 300),
  place_id text check (place_id is null or char_length(place_id) <= 120),
  place_name text check (place_name is null or char_length(place_name) <= 160),
  category text check (category is null or char_length(category) <= 60),
  duration_ms integer check (duration_ms is null or duration_ms between 0 and 120000),
  status_code smallint check (status_code is null or status_code between 0 and 599),
  success boolean not null default true,
  error_message text check (error_message is null or char_length(error_message) <= 500),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  event_bucket bigint not null,
  created_at timestamptz not null default now()
);

create unique index if not exists admin_operation_events_deduplicate_idx
  on public.admin_operation_events(
    visitor_id,
    event_type,
    feature,
    coalesce(route, ''),
    coalesce(place_id, ''),
    event_bucket
  );
create index if not exists admin_operation_events_created_idx
  on public.admin_operation_events(created_at desc);
create index if not exists admin_operation_events_type_created_idx
  on public.admin_operation_events(event_type, created_at desc);
create index if not exists admin_operation_events_slow_api_idx
  on public.admin_operation_events(duration_ms desc, created_at desc)
  where event_type = 'api_request';

create table if not exists public.place_information_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid references auth.users(id) on delete set null,
  visitor_id uuid not null,
  platform text not null check (platform in ('web', 'android', 'ios')),
  place_id text not null check (char_length(place_id) between 1 and 120),
  place_name text not null check (char_length(place_name) between 1 and 160),
  category text check (category is null or char_length(category) <= 60),
  address text check (address is null or char_length(address) <= 300),
  reason text not null check (reason in ('incorrect_info', 'closed', 'wrong_location', 'duplicate', 'other')),
  details text check (details is null or char_length(details) <= 500),
  report_bucket bigint not null,
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  handled_by uuid references auth.users(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists place_information_reports_deduplicate_idx
  on public.place_information_reports(visitor_id, place_id, reason, report_bucket);
create index if not exists place_information_reports_status_created_idx
  on public.place_information_reports(status, created_at desc);

alter table public.admin_operation_events enable row level security;
alter table public.place_information_reports enable row level security;
revoke all on public.admin_operation_events, public.place_information_reports from public, anon, authenticated;
grant all on public.admin_operation_events, public.place_information_reports to service_role;
grant usage, select on sequence public.admin_operation_events_id_seq to service_role;

create or replace function private.prune_admin_operation_events()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.admin_operation_events where created_at < now() - interval '90 days';
  return null;
end;
$$;

drop trigger if exists prune_admin_operation_events_after_insert on public.admin_operation_events;
create trigger prune_admin_operation_events_after_insert
after insert on public.admin_operation_events
for each statement execute function private.prune_admin_operation_events();

create or replace function private.prune_place_information_reports()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.place_information_reports
  where handled_at is not null and handled_at < now() - interval '1 year';
  return null;
end;
$$;

drop trigger if exists prune_place_information_reports_after_change on public.place_information_reports;
create trigger prune_place_information_reports_after_change
after insert or update on public.place_information_reports
for each statement execute function private.prune_place_information_reports();

create or replace function public.get_admin_operations_dashboard(p_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  safe_days integer := least(greatest(coalesce(p_days, 30), 1), 90);
  since_time timestamptz := now() - make_interval(days => safe_days);
  click_count bigint;
  result jsonb;
begin
  select count(*) into click_count
  from public.admin_operation_events
  where created_at >= since_time and event_type = 'place_card_click';

  select jsonb_build_object(
    'searchNoResults', count(*) filter (where event_type = 'search_no_results'),
    'placeClicks', click_count,
    'appErrors', count(*) filter (where event_type = 'app_error'),
    'appCrashes', count(*) filter (where event_type = 'app_crash'),
    'slowApiCount', count(*) filter (where event_type = 'api_request' and duration_ms >= 1500),
    'apiErrorCount', count(*) filter (where event_type = 'api_request' and not success),
    'conversions', jsonb_build_object(
      'map', jsonb_build_object(
        'count', count(*) filter (where event_type = 'map_open'),
        'rate', case when click_count = 0 then 0 else round((count(*) filter (where event_type = 'map_open'))::numeric * 100 / click_count, 1) end
      ),
      'directions', jsonb_build_object(
        'count', count(*) filter (where event_type = 'directions_open'),
        'rate', case when click_count = 0 then 0 else round((count(*) filter (where event_type = 'directions_open'))::numeric * 100 / click_count, 1) end
      ),
      'booking', jsonb_build_object(
        'count', count(*) filter (where event_type = 'booking_open'),
        'rate', case when click_count = 0 then 0 else round((count(*) filter (where event_type = 'booking_open'))::numeric * 100 / click_count, 1) end
      )
    ),
    'slowApis', coalesce((
      select jsonb_agg(to_jsonb(items) order by items.p95_ms desc)
      from (
        select
          coalesce(route, feature) as route,
          count(*) as requests,
          round(avg(duration_ms))::integer as avg_ms,
          round(percentile_cont(0.95) within group (order by duration_ms))::integer as p95_ms,
          count(*) filter (where not success) as errors
        from public.admin_operation_events
        where created_at >= since_time and event_type = 'api_request' and duration_ms is not null
        group by coalesce(route, feature)
        order by percentile_cont(0.95) within group (order by duration_ms) desc
        limit 10
      ) items
    ), '[]'::jsonb),
    'noResultQueries', coalesce((
      select jsonb_agg(to_jsonb(items) order by items.count desc)
      from (
        select feature, coalesce(route, '-') as route, count(*) as count
        from public.admin_operation_events
        where created_at >= since_time and event_type = 'search_no_results'
        group by feature, coalesce(route, '-')
        order by count(*) desc
        limit 10
      ) items
    ), '[]'::jsonb),
    'recentErrors', coalesce((
      select jsonb_agg(to_jsonb(items) order by items.created_at desc)
      from (
        select platform, feature, route, error_message, status_code, created_at
        from public.admin_operation_events
        where created_at >= since_time and event_type in ('app_error', 'app_crash')
        order by created_at desc
        limit 20
      ) items
    ), '[]'::jsonb)
  ) into result
  from public.admin_operation_events
  where created_at >= since_time;

  return result;
end;
$$;

revoke all on function public.get_admin_operations_dashboard(integer) from public, anon, authenticated;
grant execute on function public.get_admin_operations_dashboard(integer) to service_role;
