create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

create table if not exists public.spaces (
  id uuid primary key default gen_random_uuid(),
  space_type text not null check (space_type in ('personal', 'couple', 'friends', 'family')),
  name text not null check (char_length(name) between 1 and 80),
  created_by uuid not null references auth.users(id) on delete cascade,
  invite_code_hash text,
  invite_expires_at timestamptz,
  invite_used_at timestamptz,
  invite_revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists spaces_personal_owner_idx
  on public.spaces(created_by) where space_type = 'personal';
create unique index if not exists spaces_invite_code_hash_idx
  on public.spaces(invite_code_hash) where invite_code_hash is not null;

create table if not exists public.space_members (
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 24),
  role text not null check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (space_id, user_id)
);

create index if not exists space_members_user_idx
  on public.space_members(user_id, joined_at desc);
create index if not exists space_members_space_idx
  on public.space_members(space_id, joined_at);

create table if not exists public.space_milestones (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  milestone_date date not null,
  repeats_yearly boolean not null default false,
  note text check (note is null or char_length(note) <= 500),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists space_milestones_space_date_idx
  on public.space_milestones(space_id, milestone_date);

create table if not exists public.space_invite_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  attempted_at timestamptz not null default now(),
  succeeded boolean not null default false
);

create index if not exists space_invite_attempts_user_time_idx
  on public.space_invite_attempts(user_id, attempted_at desc);

create table if not exists public.space_reservation_plans (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  purpose text not null check (char_length(purpose) between 1 and 40),
  reservation_date date not null,
  party_size integer not null check (party_size between 1 and 50),
  budget_per_person integer check (
    budget_per_person is null or budget_per_person between 0 and 10000000
  ),
  note text check (note is null or char_length(note) <= 1000),
  status text not null default 'voting'
    check (status in ('voting', 'ready', 'requested', 'confirmed', 'cancelled')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists space_reservation_plans_space_date_idx
  on public.space_reservation_plans(space_id, reservation_date desc, created_at desc);

create table if not exists public.space_reservation_candidates (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.space_reservation_plans(id) on delete cascade,
  place_source text not null default 'manual' check (char_length(place_source) <= 30),
  place_id text check (place_id is null or char_length(place_id) <= 160),
  place_name text not null check (char_length(place_name) between 1 and 120),
  category text check (category is null or char_length(category) <= 40),
  address text check (address is null or char_length(address) <= 240),
  starts_at timestamptz not null,
  external_reservation_url text check (
    external_reservation_url is null or char_length(external_reservation_url) <= 1000
  ),
  is_selected boolean not null default false,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists space_reservation_candidates_plan_idx
  on public.space_reservation_candidates(plan_id, created_at);
create unique index if not exists space_reservation_one_selected_candidate_idx
  on public.space_reservation_candidates(plan_id) where is_selected;

create table if not exists public.space_reservation_votes (
  candidate_id uuid not null references public.space_reservation_candidates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (candidate_id, user_id)
);

create index if not exists space_reservation_votes_user_idx
  on public.space_reservation_votes(user_id, created_at desc);

create table if not exists public.space_calendar_events (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  starts_at timestamptz not null,
  ends_at timestamptz,
  all_day boolean not null default false,
  location text check (location is null or char_length(location) <= 160),
  note text check (note is null or char_length(note) <= 1000),
  color text not null default 'red' check (color in ('red', 'blue', 'lime', 'pink', 'black')),
  created_by uuid not null references auth.users(id) on delete cascade,
  reservation_plan_id uuid references public.space_reservation_plans(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);

create index if not exists space_calendar_events_space_start_idx
  on public.space_calendar_events(space_id, starts_at);
create unique index if not exists space_calendar_events_reservation_plan_idx
  on public.space_calendar_events(reservation_plan_id)
  where reservation_plan_id is not null;

create table if not exists public.place_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text not null check (char_length(visitor_id) between 1 and 120),
  source_id text not null check (char_length(source_id) between 1 and 160),
  name text not null check (char_length(name) between 1 and 160),
  region text not null default '전국' check (char_length(region) <= 40),
  city text check (city is null or char_length(city) <= 80),
  category text not null check (char_length(category) <= 40),
  address text check (address is null or char_length(address) <= 300),
  image_url text check (image_url is null or char_length(image_url) <= 1200),
  event_type text not null check (event_type in ('view', 'detail', 'outbound', 'favorite')),
  created_at timestamptz not null default now()
);

create index if not exists place_activity_events_recent_idx
  on public.place_activity_events(created_at desc);
create index if not exists place_activity_events_source_idx
  on public.place_activity_events(source_id, created_at desc);
