create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

create table if not exists public.spaces (
  id uuid primary key default gen_random_uuid(),
  space_type text not null check (space_type in ('personal', 'couple', 'friends', 'family')),
  name text not null check (char_length(name) between 1 and 80),
  created_by uuid not null references auth.users(id) on delete cascade,
  invite_code_hash text,
  invite_expires_at timestamptz,
  invite_used_at timestamptz,
  invite_revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists spaces_personal_owner_idx
  on public.spaces(created_by) where space_type = 'personal';
create unique index if not exists spaces_invite_code_hash_idx
  on public.spaces(invite_code_hash) where invite_code_hash is not null;

create table if not exists public.space_members (
  space_id uuid not null references public.spaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 24),
  role text not null check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  primary key (space_id, user_id)
);

create index if not exists space_members_user_idx
  on public.space_members(user_id, joined_at desc);
create index if not exists space_members_space_idx
  on public.space_members(space_id, joined_at);

create table if not exists public.space_calendar_events (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  starts_at timestamptz not null,
  ends_at timestamptz,
  all_day boolean not null default false,
  location text check (location is null or char_length(location) <= 160),
  note text check (note is null or char_length(note) <= 1000),
  color text not null default 'red' check (color in ('red', 'blue', 'lime', 'pink', 'black')),
  created_by uuid not null references auth.users(id) on delete cascade,
  reservation_plan_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);

create index if not exists space_calendar_events_space_start_idx
  on public.space_calendar_events(space_id, starts_at);

create table if not exists public.space_milestones (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 80),
  milestone_date date not null,
  repeats_yearly boolean not null default false,
  note text check (note is null or char_length(note) <= 500),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists space_milestones_space_date_idx
  on public.space_milestones(space_id, milestone_date);

create table if not exists public.space_invite_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  attempted_at timestamptz not null default now(),
  succeeded boolean not null default false
);

create index if not exists space_invite_attempts_user_time_idx
  on public.space_invite_attempts(user_id, attempted_at desc);

create table if not exists public.space_reservation_plans (
  id uuid primary key default gen_random_uuid(),
  space_id uuid not null references public.spaces(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  purpose text not null check (char_length(purpose) between 1 and 40),
  reservation_date date not null,
  party_size integer not null check (party_size between 1 and 50),
  budget_per_person integer check (budget_per_person is null or budget_per_person between 0 and 10000000),
  note text check (note is null or char_length(note) <= 1000),
  status text not null default 'voting'
    check (status in ('voting', 'ready', 'requested', 'confirmed', 'cancelled')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists space_reservation_plans_space_date_idx
  on public.space_reservation_plans(space_id, reservation_date desc, created_at desc);

create table if not exists public.space_reservation_candidates (
  id uuid primary key default gen_random_uuid(),
  plan_id uuid not null references public.space_reservation_plans(id) on delete cascade,
  place_source text not null default 'manual' check (char_length(place_source) <= 30),
  place_id text check (place_id is null or char_length(place_id) <= 160),
  place_name text not null check (char_length(place_name) between 1 and 120),
  category text check (category is null or char_length(category) <= 40),
  address text check (address is null or char_length(address) <= 240),
  starts_at timestamptz not null,
  external_reservation_url text check (external_reservation_url is null or char_length(external_reservation_url) <= 1000),
  is_selected boolean not null default false,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists space_reservation_candidates_plan_idx
  on public.space_reservation_candidates(plan_id, created_at);
create unique index if not exists space_reservation_one_selected_candidate_idx
  on public.space_reservation_candidates(plan_id) where is_selected;

create table if not exists public.space_reservation_votes (
  candidate_id uuid not null references public.space_reservation_candidates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (candidate_id, user_id)
);

create index if not exists space_reservation_votes_user_idx
  on public.space_reservation_votes(user_id, created_at desc);

alter table public.space_calendar_events
  drop constraint if exists space_calendar_events_reservation_plan_id_fkey;
alter table public.space_calendar_events
  add constraint space_calendar_events_reservation_plan_id_fkey
  foreign key (reservation_plan_id) references public.space_reservation_plans(id) on delete cascade;
create unique index if not exists space_calendar_events_reservation_plan_idx
  on public.space_calendar_events(reservation_plan_id) where reservation_plan_id is not null;

create table if not exists public.place_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text not null check (char_length(visitor_id) between 1 and 120),
  source_id text not null check (char_length(source_id) between 1 and 160),
  name text not null check (char_length(name) between 1 and 160),
  region text not null default '전국' check (char_length(region) <= 40),
  city text check (city is null or char_length(city) <= 80),
  category text not null check (char_length(category) <= 40),
  address text check (address is null or char_length(address) <= 300),
  image_url text check (image_url is null or char_length(image_url) <= 1200),
  event_type text not null check (event_type in ('view', 'detail', 'outbound', 'favorite')),
  created_at timestamptz not null default now()
);

create index if not exists place_activity_events_recent_idx
  on public.place_activity_events(created_at desc);
create index if not exists place_activity_events_source_idx
  on public.place_activity_events(source_id, created_at desc);

create table if not exists public.keyword_search_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text not null check (char_length(visitor_id) between 1 and 120),
  keyword text not null check (char_length(keyword) between 1 and 80),
  source text not null check (source in ('search', 'trend')),
  created_at timestamptz not null default now()
);

create index if not exists keyword_search_events_recent_idx
  on public.keyword_search_events(created_at desc);
create index if not exists keyword_search_events_keyword_idx
  on public.keyword_search_events(keyword, created_at desc);

create or replace function private.is_space_member(target_space_id uuid, target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select target_user_id is not null and exists (
    select 1 from public.space_members
    where space_id = target_space_id and user_id = target_user_id
  );
$$;

create or replace function private.is_space_owner(target_space_id uuid, target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select target_user_id is not null and exists (
    select 1 from public.space_members
    where space_id = target_space_id and user_id = target_user_id and role = 'owner'
  );
$$;

grant execute on function private.is_space_member(uuid, uuid) to authenticated, service_role;
grant execute on function private.is_space_owner(uuid, uuid) to authenticated, service_role;

alter table public.spaces enable row level security;
alter table public.space_members enable row level security;
alter table public.space_calendar_events enable row level security;
alter table public.space_milestones enable row level security;
alter table public.space_invite_attempts enable row level security;
alter table public.space_reservation_plans enable row level security;
alter table public.space_reservation_candidates enable row level security;
alter table public.space_reservation_votes enable row level security;
alter table public.place_activity_events enable row level security;
alter table public.keyword_search_events enable row level security;

drop policy if exists spaces_member_select on public.spaces;
create policy spaces_member_select on public.spaces
  for select to authenticated
  using ((select private.is_space_member(id)));

drop policy if exists space_members_member_select on public.space_members;
create policy space_members_member_select on public.space_members
  for select to authenticated
  using ((select private.is_space_member(space_id)));

drop policy if exists calendar_member_select on public.space_calendar_events;
create policy calendar_member_select on public.space_calendar_events
  for select to authenticated
  using ((select private.is_space_member(space_id)));
drop policy if exists calendar_member_insert on public.space_calendar_events;
create policy calendar_member_insert on public.space_calendar_events
  for insert to authenticated
  with check ((select auth.uid()) = created_by and (select private.is_space_member(space_id)));
drop policy if exists calendar_member_update on public.space_calendar_events;
create policy calendar_member_update on public.space_calendar_events
  for update to authenticated
  using ((select private.is_space_member(space_id)))
  with check ((select private.is_space_member(space_id)));
drop policy if exists calendar_member_delete on public.space_calendar_events;
create policy calendar_member_delete on public.space_calendar_events
  for delete to authenticated
  using ((select private.is_space_member(space_id)));

drop policy if exists milestones_member_select on public.space_milestones;
create policy milestones_member_select on public.space_milestones
  for select to authenticated using ((select private.is_space_member(space_id)));
drop policy if exists milestones_member_write on public.space_milestones;
create policy milestones_member_write on public.space_milestones
  for all to authenticated
  using ((select private.is_space_member(space_id)))
  with check ((select auth.uid()) = created_by and (select private.is_space_member(space_id)));

drop policy if exists reservation_plans_member_select on public.space_reservation_plans;
create policy reservation_plans_member_select on public.space_reservation_plans
  for select to authenticated using ((select private.is_space_member(space_id)));
drop policy if exists reservation_candidates_member_select on public.space_reservation_candidates;
create policy reservation_candidates_member_select on public.space_reservation_candidates
  for select to authenticated using (exists (
    select 1 from public.space_reservation_plans p
    where p.id = plan_id and (select private.is_space_member(p.space_id))
  ));
drop policy if exists reservation_votes_member_select on public.space_reservation_votes;
create policy reservation_votes_member_select on public.space_reservation_votes
  for select to authenticated using (exists (
    select 1
    from public.space_reservation_candidates c
    join public.space_reservation_plans p on p.id = c.plan_id
    where c.id = candidate_id and (select private.is_space_member(p.space_id))
  ));

revoke all on public.spaces, public.space_members, public.space_invite_attempts,
  public.space_reservation_plans, public.space_reservation_candidates,
  public.space_reservation_votes, public.place_activity_events,
  public.keyword_search_events from anon, authenticated;
grant select on public.spaces, public.space_members, public.space_calendar_events,
  public.space_milestones, public.space_reservation_plans,
  public.space_reservation_candidates, public.space_reservation_votes to authenticated;
grant insert, update, delete on public.space_calendar_events, public.space_milestones to authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.ensure_personal_space(p_display_name text default null)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  result_id uuid;
  safe_name text;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  perform pg_advisory_xact_lock(hashtextextended(actor::text, 0));

  select id into result_id
  from public.spaces
  where created_by = actor and space_type = 'personal'
  limit 1;

  if result_id is null then
    insert into public.spaces(space_type, name, created_by)
    values ('personal', '나의 공간', actor)
    returning id into result_id;
  end if;

  safe_name := left(coalesce(nullif(btrim(p_display_name), ''), '나'), 24);
  insert into public.space_members(space_id, user_id, display_name, role)
  values (result_id, actor, safe_name, 'owner')
  on conflict (space_id, user_id) do update set display_name = excluded.display_name;

  return result_id;
end;
$$;

create or replace function public.list_my_spaces(p_display_name text default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  payload jsonb;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  perform public.ensure_personal_space(p_display_name);

  select jsonb_build_object(
    'user_id', actor,
    'spaces', coalesce(jsonb_agg(jsonb_build_object(
      'id', s.id,
      'space_type', s.space_type,
      'name', s.name,
      'member_role', me.role,
      'member_count', (select count(*) from public.space_members x where x.space_id = s.id),
      'invite_expires_at', s.invite_expires_at,
      'created_at', s.created_at,
      'legacy_couple', false
    ) order by case s.space_type when 'personal' then 0 when 'couple' then 1 when 'friends' then 2 else 3 end, s.created_at desc), '[]'::jsonb)
  ) into payload
  from public.space_members me
  join public.spaces s on s.id = me.space_id
  where me.user_id = actor;

  return payload;
end;
$$;

create or replace function public.create_shared_space(
  p_type text,
  p_name text,
  p_display_name text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  normalized_type text := lower(btrim(coalesce(p_type, '')));
  code text;
  expires_at timestamptz := now() + interval '24 hours';
  new_space_id uuid;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  if normalized_type not in ('couple', 'friends', 'family') then
    raise exception '커플, 친구 또는 가족 공간을 선택해 주세요.';
  end if;
  if char_length(btrim(coalesce(p_name, ''))) not between 1 and 80 then
    raise exception '공간 이름은 1자 이상 80자 이하로 입력해 주세요.';
  end if;
  if char_length(btrim(coalesce(p_display_name, ''))) not between 1 and 24 then
    raise exception '닉네임은 1자 이상 24자 이하로 입력해 주세요.';
  end if;
  if normalized_type = 'couple' and exists (
    select 1 from public.space_members me join public.spaces s on s.id = me.space_id
    where me.user_id = actor and s.space_type = 'couple'
  ) then
    raise exception '이미 참여 중인 커플 공간이 있습니다.';
  end if;

  code := upper(encode(gen_random_bytes(16), 'hex'));
  insert into public.spaces(space_type, name, created_by, invite_code_hash, invite_expires_at)
  values (normalized_type, btrim(p_name), actor, encode(digest(code, 'sha256'), 'hex'), expires_at)
  returning id into new_space_id;

  insert into public.space_members(space_id, user_id, display_name, role)
  values (new_space_id, actor, btrim(p_display_name), 'owner');

  return jsonb_build_object('space_id', new_space_id, 'invite_code', code, 'invite_expires_at', expires_at);
end;
$$;

create or replace function public.refresh_space_invite(p_space_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  target_type text;
  code text;
  expires_at timestamptz := now() + interval '24 hours';
  member_count integer;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  select s.space_type into target_type
  from public.spaces s
  join public.space_members me on me.space_id = s.id
  where s.id = p_space_id and me.user_id = actor and me.role = 'owner'
  for update of s;

  if target_type is null then raise exception '초대 코드를 만들 권한이 없습니다.'; end if;
  if target_type = 'personal' then raise exception '개인 공간에는 다른 사람을 초대할 수 없습니다.'; end if;
  select count(*) into member_count from public.space_members where space_id = p_space_id;
  if member_count >= case when target_type = 'couple' then 2 else 20 end then
    raise exception '이 공간의 참여 인원이 모두 찼습니다.';
  end if;

  code := upper(encode(gen_random_bytes(16), 'hex'));
  update public.spaces
  set invite_code_hash = encode(digest(code, 'sha256'), 'hex'),
      invite_expires_at = expires_at,
      invite_used_at = null,
      invite_revoked_at = null,
      updated_at = now()
  where id = p_space_id;

  return jsonb_build_object('space_id', p_space_id, 'invite_code', code, 'invite_expires_at', expires_at);
end;
$$;

create or replace function public.join_shared_space(p_invite_code text, p_display_name text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  code text := upper(regexp_replace(coalesce(p_invite_code, ''), '\s+', '', 'g'));
  target public.spaces%rowtype;
  attempts integer;
  member_count integer;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  delete from public.space_invite_attempts where attempted_at < now() - interval '30 days';
  select count(*) into attempts from public.space_invite_attempts
  where user_id = actor and attempted_at > now() - interval '15 minutes' and not succeeded;
  if attempts >= 10 then
    return jsonb_build_object('error', '초대 코드 입력 횟수를 초과했습니다. 15분 후 다시 시도해 주세요.');
  end if;
  if code !~ '^[0-9A-F]{32}$' then
    insert into public.space_invite_attempts(user_id, succeeded) values (actor, false);
    return jsonb_build_object('error', '초대 코드는 영문 대문자와 숫자로 된 32자리입니다.');
  end if;
  if char_length(btrim(coalesce(p_display_name, ''))) not between 1 and 24 then
    return jsonb_build_object('error', '닉네임은 1자 이상 24자 이하로 입력해 주세요.');
  end if;

  select * into target from public.spaces
  where invite_code_hash = encode(digest(code, 'sha256'), 'hex')
    and invite_used_at is null and invite_revoked_at is null
    and invite_expires_at > now()
  for update;

  if target.id is null then
    insert into public.space_invite_attempts(user_id, succeeded) values (actor, false);
    return jsonb_build_object('error', '초대 코드가 올바르지 않거나 만료되었습니다.');
  end if;
  if exists (select 1 from public.space_members where space_id = target.id and user_id = actor) then
    return jsonb_build_object('error', '이미 참여 중인 공간입니다.');
  end if;
  if target.space_type = 'couple' and exists (
    select 1 from public.space_members me join public.spaces s on s.id = me.space_id
    where me.user_id = actor and s.space_type = 'couple'
  ) then
    return jsonb_build_object('error', '이미 참여 중인 커플 공간이 있습니다.');
  end if;
  select count(*) into member_count from public.space_members where space_id = target.id;
  if member_count >= case when target.space_type = 'couple' then 2 else 20 end then
    return jsonb_build_object('error', '이 공간의 참여 인원이 모두 찼습니다.');
  end if;

  insert into public.space_members(space_id, user_id, display_name, role)
  values (target.id, actor, btrim(p_display_name), 'member');
  update public.spaces set invite_used_at = now(), invite_revoked_at = now(),
    invite_code_hash = null, invite_expires_at = null, updated_at = now()
  where id = target.id;
  insert into public.space_invite_attempts(user_id, succeeded) values (actor, true);
  return jsonb_build_object('space_id', target.id);
end;
$$;

create or replace function public.leave_shared_space(p_space_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  target_type text;
  target_role text;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  select s.space_type, me.role into target_type, target_role
  from public.spaces s join public.space_members me on me.space_id = s.id
  where s.id = p_space_id and me.user_id = actor
  for update of s;
  if target_type is null then raise exception '참여 중인 공간을 찾을 수 없습니다.'; end if;
  if target_type = 'personal' then raise exception '기본 개인 공간은 삭제할 수 없습니다.'; end if;
  if target_role = 'owner' then
    delete from public.spaces where id = p_space_id;
  else
    delete from public.space_members where space_id = p_space_id and user_id = actor;
  end if;
  return true;
end;
$$;

create or replace function public.list_my_reservations(p_space_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := auth.uid();
  result_plans jsonb := '[]'::jsonb;
  plan_row record;
  candidates jsonb;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  for plan_row in
    select p.*, s.name as space_name, s.space_type, (p.created_by = actor) as can_manage
    from public.space_reservation_plans p
    join public.spaces s on s.id = p.space_id
    join public.space_members me on me.space_id = p.space_id and me.user_id = actor
    where p_space_id is null or p.space_id = p_space_id
    order by p.reservation_date desc, p.created_at desc
  loop
    select coalesce(jsonb_agg(candidate_payload order by selected_sort desc, vote_sort desc, created_sort), '[]'::jsonb)
    into candidates
    from (
      select jsonb_build_object(
        'id', c.id,
        'plan_id', c.plan_id,
        'place_source', c.place_source,
        'place_id', c.place_id,
        'place_name', c.place_name,
        'category', c.category,
        'address', c.address,
        'starts_at', c.starts_at,
        'external_reservation_url', c.external_reservation_url,
        'is_selected', c.is_selected,
        'created_by', c.created_by,
        'created_at', c.created_at,
        'vote_count', (select count(*) from public.space_reservation_votes v where v.candidate_id = c.id),
        'voted_by_me', exists(select 1 from public.space_reservation_votes v where v.candidate_id = c.id and v.user_id = actor),
        'voters', coalesce((
          select jsonb_agg(jsonb_build_object('display_name', sm.display_name) order by v.created_at)
          from public.space_reservation_votes v
          join public.space_members sm on sm.space_id = plan_row.space_id and sm.user_id = v.user_id
          where v.candidate_id = c.id
        ), '[]'::jsonb)
      ) as candidate_payload,
      c.is_selected as selected_sort,
      (select count(*) from public.space_reservation_votes v where v.candidate_id = c.id) as vote_sort,
      c.created_at as created_sort
      from public.space_reservation_candidates c
      where c.plan_id = plan_row.id
    ) ranked;

    result_plans := result_plans || jsonb_build_array(
      to_jsonb(plan_row) - 'invite_code_hash' || jsonb_build_object(
        'reservation_date', to_char(plan_row.reservation_date, 'YYYY-MM-DD'),
        'candidates', candidates
      )
    );
  end loop;
  return jsonb_build_object('user_id', actor, 'plans', result_plans);
end;
$$;

create or replace function public.create_reservation_plan(
  p_space_id uuid,
  p_title text,
  p_purpose text,
  p_reservation_date date,
  p_party_size integer,
  p_budget_per_person integer default null,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := auth.uid(); new_id uuid;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  if not private.is_space_member(p_space_id, actor) then raise exception '참여 중인 공간을 찾을 수 없습니다.'; end if;
  if p_reservation_date < (now() at time zone 'Asia/Seoul')::date then raise exception '예약 날짜는 오늘 이후로 선택해 주세요.'; end if;
  if char_length(btrim(coalesce(p_title, ''))) not between 1 and 100 then raise exception '계획 이름을 확인해 주세요.'; end if;
  if char_length(btrim(coalesce(p_purpose, ''))) not between 1 and 40 then raise exception '외출 목적을 확인해 주세요.'; end if;
  if p_party_size not between 1 and 50 then raise exception '인원은 1명 이상 50명 이하로 선택해 주세요.'; end if;
  if p_budget_per_person is not null and p_budget_per_person not between 0 and 10000000 then raise exception '예산을 확인해 주세요.'; end if;
  insert into public.space_reservation_plans(space_id, title, purpose, reservation_date, party_size, budget_per_person, note, created_by)
  values (p_space_id, btrim(p_title), btrim(p_purpose), p_reservation_date, p_party_size, p_budget_per_person, nullif(btrim(p_note), ''), actor)
  returning id into new_id;
  return jsonb_build_object('plan_id', new_id, 'status', 'voting');
end;
$$;

create or replace function public.add_reservation_candidate(
  p_plan_id uuid,
  p_place_source text,
  p_place_id text,
  p_place_name text,
  p_category text,
  p_address text,
  p_starts_at timestamptz,
  p_external_reservation_url text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := auth.uid(); plan_row public.space_reservation_plans%rowtype; new_id uuid; candidate_count integer;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  select p.* into plan_row from public.space_reservation_plans p
  where p.id = p_plan_id and private.is_space_member(p.space_id, actor);
  if plan_row.id is null then raise exception '접근할 수 있는 예약 계획을 찾지 못했습니다.'; end if;
  if plan_row.status not in ('voting', 'ready') then raise exception '예약 요청 전 단계에서만 후보를 추가할 수 있습니다.'; end if;
  if char_length(btrim(coalesce(p_place_name, ''))) not between 1 and 120 then raise exception '장소명을 확인해 주세요.'; end if;
  if (p_starts_at at time zone 'Asia/Seoul')::date <> plan_row.reservation_date then raise exception '후보 방문 시간은 예약 계획 날짜와 같아야 합니다.'; end if;
  if p_external_reservation_url is not null and p_external_reservation_url !~* '^https?://[^[:space:]]+$' then raise exception '외부 예약 링크는 올바른 http 또는 https 주소여야 합니다.'; end if;
  select count(*) into candidate_count from public.space_reservation_candidates where plan_id = p_plan_id;
  if candidate_count >= 20 then raise exception '하나의 예약 계획에는 후보를 최대 20곳까지 추가할 수 있습니다.'; end if;
  insert into public.space_reservation_candidates(plan_id, place_source, place_id, place_name, category, address, starts_at, external_reservation_url, created_by)
  values (p_plan_id, left(coalesce(nullif(btrim(p_place_source), ''), 'manual'), 30), nullif(btrim(p_place_id), ''), btrim(p_place_name), nullif(btrim(p_category), ''), nullif(btrim(p_address), ''), p_starts_at, nullif(btrim(p_external_reservation_url), ''), actor)
  returning id into new_id;
  return jsonb_build_object('candidate_id', new_id);
end;
$$;

create or replace function public.toggle_reservation_vote(p_candidate_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := auth.uid(); target_space uuid; target_status text; removed integer;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  select p.space_id, p.status into target_space, target_status
  from public.space_reservation_candidates c join public.space_reservation_plans p on p.id = c.plan_id
  where c.id = p_candidate_id;
  if target_space is null or not private.is_space_member(target_space, actor) then raise exception '예약 후보를 찾을 수 없습니다.'; end if;
  if target_status not in ('voting', 'ready') then raise exception '예약 요청 전 단계에서만 투표할 수 있습니다.'; end if;
  delete from public.space_reservation_votes where candidate_id = p_candidate_id and user_id = actor;
  get diagnostics removed = row_count;
  if removed = 0 then
    insert into public.space_reservation_votes(candidate_id, user_id) values (p_candidate_id, actor) on conflict do nothing;
    return jsonb_build_object('voted', true);
  end if;
  return jsonb_build_object('voted', false);
end;
$$;

create or replace function public.finalize_reservation_plan(p_plan_id uuid, p_candidate_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := auth.uid(); plan_row public.space_reservation_plans%rowtype; candidate_row public.space_reservation_candidates%rowtype;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  select * into plan_row from public.space_reservation_plans where id = p_plan_id for update;
  if plan_row.id is null or plan_row.created_by <> actor then raise exception '예약 계획을 만든 대표자만 최종 상태를 변경할 수 있습니다.'; end if;
  if not private.is_space_member(plan_row.space_id, actor) then raise exception '접근할 수 있는 예약 계획을 찾지 못했습니다.'; end if;
  if plan_row.status not in ('voting', 'ready') then raise exception '예약 요청 전 단계에서만 최종 장소를 변경할 수 있습니다.'; end if;
  select * into candidate_row from public.space_reservation_candidates where id = p_candidate_id and plan_id = p_plan_id for update;
  if candidate_row.id is null then raise exception '선택할 예약 후보를 찾을 수 없습니다.'; end if;
  update public.space_reservation_candidates set is_selected = false where plan_id = p_plan_id;
  update public.space_reservation_candidates set is_selected = true where id = p_candidate_id;
  update public.space_reservation_plans set status = 'ready', updated_at = now() where id = p_plan_id;
  insert into public.space_calendar_events(space_id, title, starts_at, all_day, location, note, color, created_by, reservation_plan_id)
  values (plan_row.space_id, '[함께 예약] ' || plan_row.title, candidate_row.starts_at, false, candidate_row.address, '선택 장소: ' || candidate_row.place_name, 'blue', actor, p_plan_id)
  on conflict (reservation_plan_id) where reservation_plan_id is not null
  do update set title = excluded.title, starts_at = excluded.starts_at, location = excluded.location, note = excluded.note, updated_at = now();
  return jsonb_build_object('status', 'ready', 'candidate_id', p_candidate_id, 'calendar_saved', true);
end;
$$;

create or replace function public.update_reservation_status(p_plan_id uuid, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := auth.uid(); plan_row public.space_reservation_plans%rowtype; normalized text := lower(btrim(coalesce(p_status, ''))); has_selected boolean;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  if normalized not in ('requested', 'confirmed', 'cancelled') then raise exception '예약 요청 중, 예약 확정 또는 취소 상태만 선택할 수 있습니다.'; end if;
  select * into plan_row from public.space_reservation_plans where id = p_plan_id for update;
  if plan_row.id is null or plan_row.created_by <> actor then raise exception '예약 계획을 만든 대표자만 최종 상태를 변경할 수 있습니다.'; end if;
  select exists(select 1 from public.space_reservation_candidates where plan_id = p_plan_id and is_selected) into has_selected;
  if normalized <> 'cancelled' and not has_selected then raise exception '먼저 투표 결과에서 최종 장소를 확정해 주세요.'; end if;
  if not ((normalized = 'requested' and plan_row.status = 'ready') or (normalized = 'confirmed' and plan_row.status = 'requested') or (normalized = 'cancelled' and plan_row.status not in ('confirmed', 'cancelled'))) then
    raise exception '현재 단계에서는 선택한 예약 상태로 변경할 수 없습니다.';
  end if;
  update public.space_reservation_plans set status = normalized, updated_at = now() where id = p_plan_id;
  return jsonb_build_object('status', normalized);
end;
$$;

create or replace function public.delete_reservation_plan(p_plan_id uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare actor uuid := auth.uid(); changed integer;
begin
  if actor is null then raise exception '로그인이 필요합니다.'; end if;
  delete from public.space_reservation_plans where id = p_plan_id and created_by = actor;
  get diagnostics changed = row_count;
  if changed = 0 then raise exception '예약 계획을 만든 대표자만 삭제할 수 있습니다.'; end if;
  return true;
end;
$$;

create or replace function public.trending_places(p_limit integer default 8)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with recent as (
    select *, case event_type when 'favorite' then 5 when 'outbound' then 3 when 'detail' then 2 else 1 end as weight
    from public.place_activity_events
    where created_at > now() - interval '7 days'
  ), ranked as (
    select source_id as id, max(name) as name, max(region) as region, max(city) as city,
      max(category) as category, max(address) as address, max(image_url) as image_url,
      sum(weight)::bigint as score, count(*)::bigint as activity_count
    from recent group by source_id
    order by score desc, activity_count desc, max(created_at) desc
    limit greatest(1, least(coalesce(p_limit, 8), 30))
  )
  select coalesce(jsonb_agg(to_jsonb(ranked)), '[]'::jsonb) from ranked;
$$;

create or replace function public.trending_keywords(p_limit integer default 10)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with ranked as (
    select keyword, count(*)::bigint as search_count, max(created_at) as last_searched_at
    from public.keyword_search_events
    where created_at > now() - interval '7 days'
    group by keyword
    order by search_count desc, last_searched_at desc
    limit greatest(1, least(coalesce(p_limit, 10), 30))
  )
  select coalesce(jsonb_agg(to_jsonb(ranked)), '[]'::jsonb) from ranked;
$$;

revoke all on function public.ensure_personal_space(text), public.list_my_spaces(text),
  public.create_shared_space(text, text, text), public.refresh_space_invite(uuid),
  public.join_shared_space(text, text), public.leave_shared_space(uuid),
  public.list_my_reservations(uuid), public.create_reservation_plan(uuid, text, text, date, integer, integer, text),
  public.add_reservation_candidate(uuid, text, text, text, text, text, timestamptz, text),
  public.toggle_reservation_vote(uuid), public.finalize_reservation_plan(uuid, uuid),
  public.update_reservation_status(uuid, text), public.delete_reservation_plan(uuid),
  public.trending_places(integer), public.trending_keywords(integer) from public, anon;

grant execute on function public.ensure_personal_space(text), public.list_my_spaces(text),
  public.create_shared_space(text, text, text), public.refresh_space_invite(uuid),
  public.join_shared_space(text, text), public.leave_shared_space(uuid),
  public.list_my_reservations(uuid), public.create_reservation_plan(uuid, text, text, date, integer, integer, text),
  public.add_reservation_candidate(uuid, text, text, text, text, text, timestamptz, text),
  public.toggle_reservation_vote(uuid), public.finalize_reservation_plan(uuid, uuid),
  public.update_reservation_status(uuid, text), public.delete_reservation_plan(uuid) to authenticated;
grant execute on function public.trending_places(integer), public.trending_keywords(integer) to anon, authenticated, service_role;
