create table if not exists public.place_activity (
  id bigint generated by default as identity primary key,
  place_id text not null,
  name text not null,
  region text not null default '전국',
  city text,
  category text not null,
  address text,
  image_url text,
  event_type text not null check (event_type in ('view', 'detail', 'outbound', 'favorite')),
  visitor_id text not null,
  event_bucket bigint not null,
  created_at timestamptz not null default now()
);

alter table public.place_activity
  add column if not exists visitor_id text not null default 'legacy';
alter table public.place_activity
  add column if not exists event_bucket bigint not null default 0;

create index if not exists place_activity_place_created_idx
  on public.place_activity (place_id, created_at desc);

create unique index if not exists place_activity_deduplicate_idx
  on public.place_activity (place_id, event_type, visitor_id, event_bucket);

create table if not exists public.trending_place_scores (
  place_id text primary key,
  name text not null,
  region text not null default '전국',
  city text,
  category text not null,
  address text,
  image_url text,
  score numeric not null default 0,
  view_count bigint not null default 0,
  detail_count bigint not null default 0,
  outbound_count bigint not null default 0,
  favorite_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.place_activity enable row level security;
alter table public.trending_place_scores enable row level security;

drop policy if exists "public can create place activity" on public.place_activity;
create policy "public can create place activity"
  on public.place_activity
  for insert
  to anon, authenticated
  with check (event_type in ('view', 'detail', 'outbound', 'favorite'));

drop policy if exists "public can read trending scores" on public.trending_place_scores;
create policy "public can read trending scores"
  on public.trending_place_scores
  for select
  to anon, authenticated
  using (true);

grant insert on public.place_activity to anon, authenticated;
grant usage, select on sequence public.place_activity_id_seq to anon, authenticated;
grant select on public.trending_place_scores to anon, authenticated;

create or replace view public.live_trending_places
with (security_invoker = true)
as
select
  place_id,
  name,
  region,
  city,
  category,
  address,
  image_url,
  round(
    (
      score::double precision *
      power(
        0.5::double precision,
        greatest(0, extract(epoch from (now() - updated_at))) / 259200
      )
    )::numeric,
    2
  ) as score,
  view_count,
  detail_count,
  outbound_count,
  favorite_count,
  updated_at
from public.trending_place_scores;

grant select on public.live_trending_places to anon, authenticated;

create or replace function public.update_trending_place_score()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  event_weight numeric;
begin
  event_weight := case new.event_type
    when 'view' then 1
    when 'detail' then 2
    when 'outbound' then 3
    when 'favorite' then 5
    else 0
  end;

  insert into public.trending_place_scores (
    place_id, name, region, city, category, address, image_url,
    score, view_count, detail_count, outbound_count, favorite_count, updated_at
  ) values (
    new.place_id, new.name, new.region, new.city, new.category, new.address, new.image_url,
    event_weight,
    case when new.event_type = 'view' then 1 else 0 end,
    case when new.event_type = 'detail' then 1 else 0 end,
    case when new.event_type = 'outbound' then 1 else 0 end,
    case when new.event_type = 'favorite' then 1 else 0 end,
    now()
  )
  on conflict (place_id) do update set
    name = excluded.name,
    region = excluded.region,
    city = excluded.city,
    category = excluded.category,
    address = coalesce(excluded.address, trending_place_scores.address),
    image_url = coalesce(excluded.image_url, trending_place_scores.image_url),
    score = trending_place_scores.score + event_weight,
    view_count = trending_place_scores.view_count +
      case when new.event_type = 'view' then 1 else 0 end,
    detail_count = trending_place_scores.detail_count +
      case when new.event_type = 'detail' then 1 else 0 end,
    outbound_count = trending_place_scores.outbound_count +
      case when new.event_type = 'outbound' then 1 else 0 end,
    favorite_count = trending_place_scores.favorite_count +
      case when new.event_type = 'favorite' then 1 else 0 end,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists place_activity_update_trending_score on public.place_activity;
create trigger place_activity_update_trending_score
after insert on public.place_activity
for each row execute function public.update_trending_place_score();

do $$
begin
  alter publication supabase_realtime add table public.trending_place_scores;
exception
  when duplicate_object then null;
end $$;
